FROM golang:1.22-alpine AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -trimpath -ldflags="-s -w" -o /out/velo ./cmd/velo

FROM gcr.io/distroless/static-debian12:nonroot
COPY --from=build /out/velo /usr/local/bin/velo
COPY configs/velo.yaml /etc/velo/velo.yaml
USER nonroot:nonroot
EXPOSE 8080 9100
ENTRYPOINT ["/usr/local/bin/velo"]
CMD ["serve", "--config", "/etc/velo/velo.yaml"]
